# Server identity
server_name = Lorem Ipsum
server_description = Serveur Luanti dockerisé + monitoring
motd = Bienvenue ! Lisez la landing page sur http://localhost:8080

# Gameplay network
port = 30000

# World settings
default_game = minetest
world_name = world

# Prometheus metrics listener (HTTP)
prometheus_listener_address = 0.0.0.0:30000
